# Generated by Django 3.1.1 on 2020-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='attendStd',
            field=models.ManyToManyField(blank=True, to='enrollcourse.Student'),
        ),
    ]
